#!/usr/bin/env bash
# Generates dist/.env with fresh, random secrets for docker-compose.prod.yml.
#
# Refuses to overwrite an existing .env by default: DB_OWNER_PASSWORD,
# DB_APP_PASSWORD, and DB_GRAFANA_PASSWORD are baked into their Postgres
# roles at first migration, so silently regenerating them for an
# already-deployed stack would lock the app (or Grafana) out of the
# database. Pass --force if you really mean to rotate
# everything (you'll then need to update the Postgres roles' passwords to
# match, or wipe the postgres volume for a from-scratch deploy).
set -euo pipefail

DIST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$DIST_DIR/.env"

if [[ -f "$ENV_FILE" && "${1:-}" != "--force" ]]; then
    echo "error: $ENV_FILE already exists — refusing to overwrite live secrets." >&2
    echo "Pass --force to regenerate anyway." >&2
    exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
    echo "error: openssl is required to generate secrets." >&2
    exit 1
fi

rand_hex() { openssl rand -hex "$1"; }

cat >"$ENV_FILE" <<EOF
# Generated by generate-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Contains live secrets — do not commit this file.

# --- Container image (must match what .github/workflows/docker-publish.yml pushed) ---
IMAGE=registry.example.com/your-org/imap-mcp
IMAGE_TAG=latest

# --- App ---
PORT=8080

# --- Database ---
# Compose-internal hostname/port — do not change unless you also edit
# docker-compose.prod.yml's service name.
POSTGRES_DB=imapmcp
DB_URL=jdbc:postgresql://postgres:5432/imapmcp
# Schema-owning role Flyway runs migrations as.
DB_OWNER_USER=imapmcp
DB_OWNER_PASSWORD=$(rand_hex 32)
# Least-privilege role the app connects as at runtime (created by the
# V4 migration the first time this stack comes up).
DB_APP_USER=imapmcp_app
DB_APP_PASSWORD=$(rand_hex 32)
# Read-only role, SELECT on audit_log only, for Grafana's PostgreSQL data
# source (created by the V5 migration the first time this stack comes up).
DB_GRAFANA_USER=grafana_ro
DB_GRAFANA_PASSWORD=$(rand_hex 32)

# --- Redis ---
REDIS_HOST=redis
REDIS_PORT=6379

# --- Credential encryption (self-hosted OpenBao Transit engine) ---
# OPENBAO_TOKEN cannot be auto-generated here — it's minted only after you've
# run OpenBao's one-time init/unseal/transit-setup runbook (see README.md),
# since it must be a least-privilege token scoped to the transit key below,
# not the initial root token.
OPENBAO_ADDR=http://openbao:8200
OPENBAO_TOKEN=
OPENBAO_TRANSIT_KEY=imap-mcp-dek

# --- OAuth ---
# Must be this server's real, fixed public URL in production — cannot be
# auto-generated. See the OAuth token flow note in CLAUDE.md.
OAUTH_ISSUER_URI=
# Optional statically-vetted seed client — leave OAUTH_SEED_CLIENT_ID blank
# to skip seeding one. A secret is pre-generated below either way so it's
# ready to use the moment you set a client id.
OAUTH_SEED_CLIENT_ID=
OAUTH_SEED_CLIENT_SECRET=$(rand_hex 32)
OAUTH_SEED_CLIENT_NAME=
OAUTH_SEED_CLIENT_REDIRECT_URIS=
EOF

chmod 600 "$ENV_FILE"

echo "Wrote $ENV_FILE (mode 600)."
echo "Still needs manual values before 'docker compose -f docker-compose.prod.yml up -d':"
echo "  IMAGE, OPENBAO_TOKEN (after running the OpenBao setup runbook in README.md), OAUTH_ISSUER_URI"
echo "  (and OAUTH_SEED_CLIENT_ID/NAME/REDIRECT_URIS if you want a seeded OAuth client)"
